line-length = 100
indent-width = 4
target-version = "py310"

[lint]
select = ["E", "F", "I", "UP", "B", "PT", "SIM"]
ignore = ["E501"]  # Line too long

[format]
quote-style = "single"
indent-style = "space"
