name: Lint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04           # GitHub runner tag, no patch number

    permissions:
      contents: read                # least-privilege for forks

    steps:
      # ───────────────────────────── Git checkout ────────────────────────────
      - name: Checkout code
        uses: actions/checkout@v4    # v4 = faster/safer submodule handling

      # ───────────────────────────── Node / Biome (JS+TS) ────────────────────
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18          # Frappe v15 front-end toolchain uses ≥ 18
          cache: "npm"


      # ───────────────────────────── Python / Ruff (back-end) ────────────────
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"    # v15 is tested & bundled against 3.10

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check .           # explicit sub-command, clearer in logs
